# Generated by Django 4.2.7 on 2026-02-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="folder", max_length=50)),
                ("color", models.CharField(default="blue", max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="api.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file_url", models.URLField()),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("video", "Video"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=300)),
                (
                    "size",
                    models.PositiveIntegerField(default=0, help_text="Size in bytes"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="EWiki", max_length=100)),
                ("site_description", models.TextField(blank=True)),
                (
                    "welcome_title",
                    models.CharField(default="Welcome back!", max_length=200),
                ),
                ("welcome_message", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("heading", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "content",
                    models.TextField(blank=True, help_text="Contenido HTML del editor"),
                ),
                ("banner_icon", models.CharField(default="description", max_length=50)),
                ("banner_text", models.CharField(blank=True, max_length=200)),
                (
                    "banner_gradient",
                    models.CharField(
                        default="bg-gradient-to-br from-blue-500 to-primary",
                        max_length=100,
                    ),
                ),
                ("banner_image", models.URLField(blank=True, null=True)),
                ("help_text", models.CharField(blank=True, max_length=300)),
                (
                    "help_button_text",
                    models.CharField(default="Contact Support", max_length=100),
                ),
                ("icon", models.CharField(default="description", max_length=50)),
                ("is_published", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="api.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RecentUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("icon", models.CharField(default="description", max_length=50)),
                ("icon_color", models.CharField(default="primary", max_length=50)),
                ("link", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.wikipage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="folder", max_length=50)),
                (
                    "menu_type",
                    models.CharField(
                        choices=[("main", "Main Menu"), ("category", "Category")],
                        default="main",
                        max_length=20,
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("color", models.CharField(default="blue", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="api.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WikiSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("content", models.TextField(help_text="Contenido HTML de la sección")),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("icon_color", models.CharField(default="primary", max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="api.wikipage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("page", "slug")},
            },
        ),
    ]
