# Generated by Django 4.2.7 on 2026-02-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_chatconversation_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiPageEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        help_text="Texto limpio usado para generar el embedding"
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        default=list,
                        help_text="Vector de embedding (768 dimensiones para text-embedding-004)",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-004",
                        help_text="Modelo usado para generar el embedding",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding_data",
                        to="api.wikipage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiki Page Embedding",
                "verbose_name_plural": "Wiki Page Embeddings",
            },
        ),
    ]
