# Generated by Django 4.2.7 on 2026-02-17 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_wikipageembedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wikipageembedding",
            name="embedding_model",
            field=models.CharField(
                default="gemini-embedding-001",
                help_text="Modelo usado para generar el embedding",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("reader", "Lector"), ("admin", "Administrador")],
                        default="reader",
                        max_length=20,
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
