# Generated by Django 4.2.7 on 2026-02-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_wikipageembedding_embedding_model_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
